---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  namespace: qa
spec:
  replicas: 1
  selector:
    matchLabels:
      name: front-end
  template:
    metadata:
      labels:
        name: front-end
    spec:
      containers:
      - name: front-end
        image: muffinhead.azurecr.io/test:ver
        resources:
          limits:
            cpu: 300m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 300Mi
        ports:
        - containerPort: 80
        
---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  
  labels:
    name: front-end
  namespace: qa
spec:
  type: LoadBalancer
  ports:
  - port: 80

    
  selector:
    name: front-end
---
