name: CI

on:
  - push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.AKS }}
        with:
          args: apply -f complete-demo.yaml
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.AKS }}
        with:
          args: get services -n sock-shop
            
