name: Build a Docker image and Push it to ACR

on:
  push:


  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: azure/docker-login@v1
        with:
          login-server: muffinhead.azurecr.io
          username: muffinhead
          password: jIo6qLfWcZhLcLXJC0KQRLK=42x27L1V

      - run: |
          docker build . -t muffinhead.azurecr.io/test:ver
          docker push muffinhead.azurecr.io/test:ver
          
      - uses: actions/checkout@master
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.AKS }}
        with:
          args: create namespace QA
      - uses: actions/checkout@master
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.AKS }}
        with:
          args: apply -f test.yaml
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.AKS }}
        with:
          args: apply -f  test_ser.yaml
