on: [push]
name: databrideployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CRED }}
      - uses: Azure/CLI@v1
        with:
          inlineScript: |
            #!/bin/bash 
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            kubectl get pods

          
            
