name: Build a Docker image and Push it to ACR

on:
  push:


  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: muffinhead.azurecr.io
          username: muffinhead
          password: jIo6qLfWcZhLcLXJC0KQRLK=42x27L1V

      - run: |
          docker build . -t muffinhead.azurecr.io/test:ver
          docker push muffinhead.azurecr.io/test:ver
          

      - uses: actions/checkout@master
      
      
      
      
      
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.AKS }}
        with:
          args: apply -f dev.yaml
          
      - name: Sleep for 30 seconds
        run: sleep 10s
        shell: bash
          
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.AKS }}
        with:
          args: get services -n dev       
          
          
          
          
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.AKS }}
        with:
          args: apply -f qa.yaml
          
      - name: Sleep for 10 seconds
        run: sleep 30s
        shell: bash          
          

      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.AKS }}
        with:
          args: get services -n qa
          
          
          
          
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.AKS }}
        with:
          args: apply -f staging.yaml
          
      - name: Sleep for 10 seconds
        run: sleep 30s
        shell: bash          

      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.AKS }}
        with:
          args: get services -n staging
