name: Build a Docker image and Push it to ACR

on:
  push:


  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: azure/docker-login@v1
        with:
          login-server: muffinhead.azurecr.io
          username: muffinhead
          password: jIo6qLfWcZhLcLXJC0KQRLK=42x27L1V

      - run: |
          docker build . -t muffinhead.azurecr.io/appdb:${{ github.sha }}
          docker push muffinhead.azurecr.io/appdb:${{ github.sha }}
